export const BUSINESS = {
  name: "Impronta Elettrica",
  owner: "Troia Cesario",
  legal: "Impronta Elettrica di Troia Cesario",
  role: "Elettricista",
  city: "Andria",
  province: "BT",
  address: "Via Scevola Muzio, 28",
  cap: "76123",
  fullAddress: "Via Scevola Muzio, 28, 76123 Andria BT",
  phoneDisplay: "327 459 6515",
  phoneTel: "+393274596515",
  whatsapp: "393274596515",
  instagram: "https://www.instagram.com/impronta_elettrica/",
  instagramHandle: "@impronta_elettrica",
  hoursLabel: "7:00 – 21:00",
  openHour: 7,
  closeHour: 21,
  responseHours: 2,
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Via+Scevola+Muzio+28+Andria",
} as const;
