/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PannelloRouteImport } from './routes/pannello'
import { Route as PreventivoRouteImport } from './routes/preventivo'
import { Route as RichiestaIdRouteImport } from './routes/richiesta.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PannelloRoute = PannelloRouteImport.update({
  id: '/pannello',
  path: '/pannello',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivoRoute = PreventivoRouteImport.update({
  id: '/preventivo',
  path: '/preventivo',
  getParentRoute: () => rootRouteImport,
} as any)
const RichiestaIdRoute = RichiestaIdRouteImport.update({
  id: '/richiesta/$id',
  path: '/richiesta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pannello': typeof PannelloRoute
  '/preventivo': typeof PreventivoRoute
  '/richiesta/$id': typeof RichiestaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pannello': typeof PannelloRoute
  '/preventivo': typeof PreventivoRoute
  '/richiesta/$id': typeof RichiestaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pannello': typeof PannelloRoute
  '/preventivo': typeof PreventivoRoute
  '/richiesta/$id': typeof RichiestaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pannello' | '/preventivo' | '/richiesta/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pannello' | '/preventivo' | '/richiesta/$id'
  id: '__root__' | '/' | '/pannello' | '/preventivo' | '/richiesta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PannelloRoute: typeof PannelloRoute
  PreventivoRoute: typeof PreventivoRoute
  RichiestaIdRoute: typeof RichiestaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pannello': {
      id: '/pannello'
      path: '/pannello'
      fullPath: '/pannello'
      preLoaderRoute: typeof PannelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventivo': {
      id: '/preventivo'
      path: '/preventivo'
      fullPath: '/preventivo'
      preLoaderRoute: typeof PreventivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/richiesta/$id': {
      id: '/richiesta/$id'
      path: '/richiesta/$id'
      fullPath: '/richiesta/$id'
      preLoaderRoute: typeof RichiestaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PannelloRoute: PannelloRoute,
  PreventivoRoute: PreventivoRoute,
  RichiestaIdRoute: RichiestaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
